### ISSUE TITLE
Archdaily

### ISSUE THREAD

**Issue by gferreroferri** [ElytraApp/IssueTracker#10]
**Article URL**

https://www.archdaily.com/979417/loch-tummel-house-wt-architecture

**Information present**
(select whatever is showing correctly)
- [ ] Title
- [ ] Author
- [ ] Cover Image
- [ ] Article Content
- [ ] Date

**Expected behavior**
missing pictures

**Screenshots**

**Additional context**

**Comment by dezinezync** [comment]
Working 
- [x] Title 
- [x] Cover Image
- [x] Date

**Comment by dezinezync** [comment]
Patched in https://github.com/dezinezync/Neptune/commit/90d284b5fd6850a2f027f9e59d646b9dd6544102

- [x] Title
- [x] Author
- [x] Cover Image
- [x] Article Content
- [x] Date
