### ISSUE TITLE
Full text not loading

### ISSUE THREAD

**Issue by gferreroferri** [ElytraApp/IssueTracker#12]
**Article URL**
https://www.europapress.es/internacional/noticia-mas-43-millones-refugiados-huido-ucrania-rusia-lanzo-invasion-20220407100645.html

**Information present**
(select whatever is showing correctly)
- [ ] Title
- [ ] Author
- [ ] Cover Image
- [ ] Article Content
- [ ] Date

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dezinezync** [comment]
Patched all
- [x] Title
- [x] Author
- [x] Cover Image
- [x] Article Content
- [x] Date
