### ISSUE TITLE
AppleInsider parsing error

### ISSUE THREAD

**Issue by xaver985** [ElytraApp/IssueTracker#13]
**Article URL**
Full URL of the article 

https://appleinsider.com/articles/22/04/12/daily-deals-april-12-200-off-samsung-galaxy-z-flip-3-5g-500-off-microsoft-surface-duo-2-5g-180-off-eufy-robovac-x8-robot-vacuum-more

**Information present**
(select whatever is showing correctly)
- [x] Title
- [x] Author
- [x] Cover Image
- [ ] Article Content
- [x] Date

**Expected behavior**
Excluding share button
**Screenshots**
![7B600751-796B-433F-9D22-70724376F34E](https://user-images.githubusercontent.com/32983060/163001581-4923f79c-7503-49f1-94ec-cdd49561351b.png)

**Additional context**

**Comment by dezinezync** [comment]
- [x] Title
- [x] Author (Patched) 
- [x] Cover Image
- [x] Article Content (Patched)
- [x] Date

**Comment by dezinezync** [comment]
@xaver985 Please check and confirm, thank you for reporting.

**Comment by xaver985** [comment]
Thank you, all the two problems have been fixed
