### ISSUE TITLE
Android Authority failed to load full text

### ISSUE THREAD

**Issue by xaver985** [ElytraApp/IssueTracker#14]
**Article URL**
Full URL of the article 

https://www.androidauthority.com/netflix-two-thumbs-up-3151352/

**Information present**
(select whatever is showing correctly)
- [x] Title
- [x] Author
- [x] Cover Image
- [ ] Article Content
- [x] Date

**Expected behavior**
All content should be parsed, but now only few
**Screenshots**
![E6790861-7AE9-4EE6-B041-B58F74D80FDA](https://user-images.githubusercontent.com/32983060/163003678-d686f3e2-bec4-41d9-bc87-7602fb68c128.png)
![BD67043A-4D11-41A3-9385-4BC4DB6324CE](https://user-images.githubusercontent.com/32983060/163003692-60e04a4f-ac6d-45c0-a9d4-a9eeaa4c6f52.png)

**Additional context**

**Comment by dezinezync** [comment]
- [x] Title
- [x] Author
- [x] Cover Image
- [x] Article Content (Patched)
- [x] Date

**Comment by dezinezync** [comment]
@xaver985 Please check and confirm, thank you for reporting.
