### ISSUE TITLE
Arstechnica

### ISSUE THREAD

**Issue by gferreroferri** [ElytraApp/IssueTracker#5]
**Article URL**

https://arstechnica.com/gadgets/2022/03/samsungs-qd-oled-tv-challenges-premium-oleds-with-2200-starting-price/

**Information present**
(select whatever is showing correctly)
- [x] Title
- [ ] Author
- [x] Cover Image
- [ ] Article Content
- [ ] Date

**Expected behavior**
Full article 

**Screenshots**

**Additional context**

**Comment by dezinezync** [comment]
Patched in https://github.com/dezinezync/Neptune/tree/e3747cfc15dc945cffff6df7fce513adad5541ed
