### ISSUE TITLE
Nyt en español

### ISSUE THREAD

**Issue by gferreroferri** [ElytraApp/IssueTracker#6]
**Article URL**

https://www.nytimes.com/es/2022/03/18/espanol/ucrania-amenaza-nuclear.html

**Information present**
(select whatever is showing correctly)
- [] Title
- [ ] Author
- [ ] Cover Image
- [ ] Article Content
- [ ] Date

**Expected behavior**
time out

**Screenshots**

**Additional context**

**Comment by dezinezync** [comment]
Patched in https://github.com/dezinezync/Neptune/tree/3a5255b95fe1b1c892a0ae9db4166cbf4886ffa5

**Comment by gferreroferri** [comment]
Still issues with nyt, timeout here for instance

https://www.nytimes.com/es/2022/03/30/espanol/ansiedad-mascarilla.html


Enviado desde mi iPad

El 30 mar 2022, a las 6:50, Nikhil Nigade ***@***.***> escribió:

﻿

Closed #6<https://github.com/ElytraApp/IssueTracker/issues/6>.

**Comment by dezinezync** [comment]
@gferreroferri I just tested it, it only times out with the old parser. The one worked as expected. 
Can you try deleting the full-text copy and re-downloading it.

**Comment by gferreroferri** [comment]
Confirmed working 🙂

Enviado desde mi iPad

El 31 mar 2022, a las 11:36, Nikhil Nigade ***@***.***> escribió:

﻿

@gferreroferri<https://github.com/gferreroferri> I just tested it, it only times out with the old parser. The one worked as expected.
Can you try deleting the full-text copy and re-downloading it.
