### ISSUE TITLE
El País 

### ISSUE THREAD

**Issue by gferreroferri** [ElytraApp/IssueTracker#8]
**Article URL**

https://elpais.com/internacional/2022-03-19/el-gobierno-de-peru-busca-revertir-la-decision-del-constitucional-de-excarcelar-a-fujimori.html

**Information present**
(select whatever is showing correctly)
- [x] Title
- [ ] Author
- [x] Cover Image
- [ ] Article Content
- [ ] Date

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dezinezync** [comment]
Patched in https://github.com/dezinezync/Neptune/tree/68366963eae1d0449cefd7d87e91640b1d0fdb81
